require('configs.mappings.native')
require('theme.nvim-theme')
require('theme.statusline')
-- require('theme.bufferline-c')
require('configs.plugins')
require('configs.neo-tree')
require('configs.treesitter')
require('configs.cmp')
require("luasnip.loaders.from_vscode").lazy_load()
require("luasnip.loaders.from_snipmate").lazy_load()
require('configs.telescope')
require('nvim-web-devicons')
-- require('configs.tree')
require('configs.comment')
require('configs.colorizer')
require('configs.indent')
require('configs.mappings.plugins')
